Adds carbondb
green-coding-solutions/eco-ci-energy-estimation pull request #61
Opened 2024-03-12 16:24 UTC by ribalba

2024-04-03 09:47 UTC, ArneTR requested changes

2024-04-03 09:47 UTC, ArneTR commented on scripts/make_measurement.sh
> +             cb_machine_uuid=$(uuidgen)
Github runners can actually be placed on the exact same machine. I do not know how `uuidgen` works under the hood but I see a fair chance for a lot of collisisone here ...?

2024-04-03 09:47 UTC, ArneTR commented on scripts/vars.sh
> +    token="your_electricity_maps_token_here"
How is this token ever gonna get filled? It is no variable?

2024-04-03 09:47 UTC, ArneTR commented on scripts/vars.sh
> +        return 1
you return a 1 here, but later you check for empty string. Is that intended and you want to proceed with 1 as a valida value?

2024-04-03 09:47 UTC, ArneTR commented on scripts/make_measurement.sh
>          echo "Invalid option -$OPTARG" >&2
Do you just want to echo here? Or maybe break?

2024-04-03 09:47 UTC, ArneTR commented on action.yml
> +      default: ''
The other optional arguments like `label` are default null. Is it possible to unify that to either?

2024-04-03 09:47 UTC, ArneTR commented on README.md
> +- `show-carbon`: (optional) (default: true)
Having this default true is nice, but how will this work without the electricitymaps token?

2024-04-03 14:44 UTC, ribalba commented on scripts/make_measurement.sh
> +             cb_machine_uuid=$(uuidgen)
```
The uuidgen command generates a Universally Unique IDentifier (UUID), a 128-bit value guaranteed to be unique over both space and time.
```

2024-04-03 14:48 UTC, ribalba commented on scripts/vars.sh
> +    token="your_electricity_maps_token_here"
Never, as electricity maps works without a token. The string is not chose very well. 
Added the option for a var

2024-04-03 14:51 UTC, ribalba commented on scripts/vars.sh
> +        return 1
1 is for error. The check for empty string was from before I wrote stuff the `stderr`

2024-04-03 15:14 UTC, ribalba commented on action.yml
> +      default: ''
I used empty string here as I can just pass it into the curl post command and not really care as the backend will then ignore it. I am not sure if handling null will make it a lot cleaner

2024-04-04 09:44 UTC, ArneTR commented
Thanks for the clarification that the token is optional.

I am not a fan however of the multiple ways to submit input. All other info is supplied via arguments. Only the Electricitymaps Token is now an exported environment var.

What is the rationale behind this?

In any case: I would favor for supplying it as argument and also making it a secret by default. Not a classic ENV.

2. These two values submitted in the PR info need a dimension.

Carbon Intensity for this location: 99 (g / kg / tons per Wh, J , kwH ?)
CO2eq emitted for this job: 0.002452 (g, kg, ton ?)

2024-04-08 09:45 UTC, ribalba commented
The problem is that when we do it with a secret/ not as env we will need to add it as a parameter to the `display_results.sh` and then it will be visible in the logs. Which is not ideal.

2024-04-08 11:14 UTC, ArneTR commented
TBD tomorrow

2024-04-09 18:22 UTC, ribalba commented
@ArneTR 

- [x] Add error text when apis fail and not fail silently
- [x] Curl will stop the script if it fails. Add detailed error checking
- [x] Token as secret

2024-04-10 22:47 UTC, merged